### ISSUE TITLE
Templates dissapear in Inbox

### ISSUE THREAD

**Issue by Erbanger** [planadecu/gmail-templates#24]
The generated templates seem to be dissapearing at random.

**Comment by planadecu** [comment]
Hi, is there any pattern that could help out to reproduce the bug?

**Comment by Erbanger** [comment]
Hi Jordy,

Thank you for you reply.

I have been trying to figure this out but can't find any patern other then
that the templates are there less often then they are not there, if I must
say around 70 % of the time they are not there.

Met vriendelijke groet,

Erik Bangert
+31652333470
<http://aangenaammakelaardij.nl/>

Op zo 27 dec. 2015 om 23:51 schreef Jordi P.S. <notifications@github.com>:

> Hi, is there any pattern that could help out to reproduce the bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/planadecu/gmail-templates/issues/24#issuecomment-167446076>
> .
>
-- 

Met vriendelijke groet,

Erik Bangert

Aangenaam Makelaardij

**Comment by planadecu** [comment]
Fixed on 1.6.0
