### ISSUE TITLE
Where are the templates stored?

### ISSUE THREAD

**Issue by rassom** [planadecu/gmail-templates#25]
(just want to make sure they don't disappear completely if I forget to export them before reinstalling my computer or if I loose the computer)

**Comment by planadecu** [comment]
Hi,

They are stored on the cloud (parse.com servers). They are linked to your
email address so they shouldn't disappear. If you want to make sure export
them with the export tool and keep the file and import it again next time.



*---Jordi PlanadecursachTel: +34 616 85 46 60*

**Comment by rassom** [comment]
@planadecu 
Sorry for the slow reply and thanks very much for taking the time to answer :-)

One suggestion:
https://chrome.google.com/webstore/detail/gorgias-email-templates-f/lmcngpkjkplipamgflhioabnhnopeabf?hl=da has support for inserting variables in templates, for example "Hi <first_name>" which will then take the first name of the sender (when replying) and put that instead for <first_name>. It saves time and makes sure one gets the name spelling right :)

Maybe it's something for your extension ?

Thanks again :+1:
